### PR TITLE
Add support for '/tag' autocomplete

### PR DESCRIPTION
**Pull request by PgBiel**
Draft because I haven't tested at all yet, but the code compiles at least (and _should_ be correct). Will test over the next few days.

Based on previous work at https://github.com/PgBiel/mentoriabot/blob/main/crates/bot/src/commands/autocomplete.rs

### CODE REVIEW

**Comment by mattfbacon** [comment]
Great. One question: this seems to suggest any tags that contain the currently typed text. Isn't it more logical to show the tags that start with the currently typed text? Can you explain the motivation for using containment instead?

**Comment by PgBiel** [comment]
Right. I thought that this could make sense when you don't remember the full name of the tag. For example, the Types and Context blog tag is `tcblog`. You might only remember the word `blog`, so searching for blog would include "tcblog" with this "fuzzy search".

I was thinking that, without searching anything, you'd, in theory, get the full list of tags, which _could_ make that unnecessary - but then I remembered that there seems to be a limit in how many options you display for autocomplete (25 I think). So maybe that's still important (you'd have to run `?tags` separately, which is what autocomplete tries to avoid).

I'm not 100% keen on this being the best option though. Gotta consider pros and cons and stuff.

**Comment by PgBiel** [comment]
Working!

https://github.com/mattfbacon/typst-bot/assets/9021226/d304cfb7-228c-4ca8-a259-a0636d68e2e3

**Comment by mattfbacon** [comment]
Thanks!

**Pull request merged**
